//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shanuMVCUserRoles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProdavnicaNamestajaEntities : DbContext
    {
        public ProdavnicaNamestajaEntities()
            : base("name=ProdavnicaNamestajaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblKategorijaNamestaja> tblKategorijaNamestajas { get; set; }
        public virtual DbSet<tblKomadNamestaja> tblKomadNamestajas { get; set; }
        public virtual DbSet<tblRacun> tblRacuns { get; set; }
        public virtual DbSet<tblSalon> tblSalons { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    }
}
