//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shanuMVCUserRoles
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblKomadNamestaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKomadNamestaja()
        {
            this.tblRacuns = new HashSet<tblRacun>();
        }
    
        public int KomadNamestajaId { get; set; }
        [Required, StringLength(1000, MinimumLength = 3, ErrorMessage = "polje morati imati minimum 3 karaktera")]
        public string Sifra { get; set; }
        [Required, StringLength(1000, MinimumLength = 3, ErrorMessage = "polje morati imati minimum 3 karaktera")]
        public string Naziv { get; set; }
        [StringLength(1000, MinimumLength = 3, ErrorMessage = "polje morati imati minimum 3 karaktera")]
        public string ZemljaProizvodnje { get; set; }
        [Range(2001, 2019)]
        public Nullable<int> GodinaProizvodnje { get; set; }
        [Required, Range(1, 99999)]
        public double JedinicnaCena { get; set; }
        [Required, Range(1, 99999)]
        public int KolicinaUMagacinu { get; set; }
        [Required]
        public int SalonId { get; set; }
        [Required]
        public int KategorijaNamestajaId { get; set; }
        public byte[] Slika { get; set; }
    
        public virtual tblKategorijaNamestaja tblKategorijaNamestaja { get; set; }
        public virtual tblSalon tblSalon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRacun> tblRacuns { get; set; }
    }
}
