//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shanuMVCUserRoles
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblKategorijaNamestaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKategorijaNamestaja()
        {
            this.tblKomadNamestajas = new HashSet<tblKomadNamestaja>();
        }
    
        public int KategroijaNamestajaId { get; set; }
        [Required, StringLength(1000, MinimumLength = 3, ErrorMessage = "polje morati imati minimum 3 karaktera")]
        public string Naziv { get; set; }
        public string Opis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKomadNamestaja> tblKomadNamestajas { get; set; }
    }
}
