//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shanuMVCUserRoles
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblRacun
    {
        
        public int RacunId { get; set; }
        public int KomadNamestajaId { get; set; }
   
        public double Porez { get; set; }

        public double UkupnaCenaSaPorezom { get; set; }

        public string DatumIVremeKupovine { get; set; }

        public string KupacKojiJeKupioRobu { get; set; }
 
        public int SalonId { get; set; }

        public double CenaBezPdv { get; set; }
 
        public int BrojRacuna { get; set; }
        public bool Uknjizeno { get; set; }

        public int Kolicina { get; set; }
    
        public virtual tblKomadNamestaja tblKomadNamestaja { get; set; }
        public virtual tblSalon tblSalon { get; set; }
    }
}
