//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shanuMVCUserRoles
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblSalon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSalon()
        {
            this.tblKomadNamestajas = new HashSet<tblKomadNamestaja>();
            this.tblRacuns = new HashSet<tblRacun>();
        }
    
        public int SalonId { get; set; }
        [Required, StringLength(1000, MinimumLength = 3, ErrorMessage = "polje morati imati minimum 3 karaktera")]
        public string Naziv { get; set; }
        [Required, StringLength(1000, MinimumLength = 3, ErrorMessage = "polje morati imati minimum 3 karaktera")]
        public string Vlasnik { get; set; }
        [Required, StringLength(1000, MinimumLength = 3, ErrorMessage = "polje morati imati minimum 3 karaktera")]
        public string Adresa { get; set; }
        public Nullable<long> Telefon { get; set; }
        [Required(ErrorMessage = "Email adresa je obavezna")]
        [EmailAddress(ErrorMessage = "Pogresna email adresa")]
        public string Email { get; set; }
        public string WebStranica { get; set; }
        [Required, Range(1, 99999)]
        public long PIB { get; set; }
        [Required, StringLength(1000, MinimumLength = 3, ErrorMessage = "polje morati imati minimum 3 karaktera")]
        public string BrojZiroRacuna { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKomadNamestaja> tblKomadNamestajas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRacun> tblRacuns { get; set; }
    }
}
